In [11]:
import streamlit as st
from datetime import datetime
import numpy as np
import pandas as pd
from tensorflow.keras.models import load_model
from sklearn.preprocessing import MinMaxScaler
from numpy import array

df=pd.read_csv('output.csv')
df=df.tail(100)
df1=df.reset_index()['high']

scaler=MinMaxScaler(feature_range=(0,1))
df1=scaler.fit_transform(np.array(df1).reshape(-1,1))

x_input = df1[:,:1]
x_input=x_input.reshape(1,-1)
temp_input=list(x_input)
temp_input=temp_input[0].tolist()

# Load the saved model
model = load_model("stock_prediction_model.h5")

# Load the scaler parameters
try:
    data = np.load("scaler_parameters.npz")
    scaler_min = data['min_']
    scaler_scale = data['scale_']

except Exception as e:
    st.error(f"Error loading the scaler parameters: {e}")
    st.stop()

# Function to scale the input date
def difference_in_days(input_date):
    reference_date = datetime.strptime("2022-12-30", "%Y-%m-%d")
    input_date = datetime.strptime(input_date, "%Y-%m-%d")
    difference_in_days = (input_date - reference_date).days
    # scaled_input = (difference_in_days - scaler_min) / scaler_scale
    return difference_in_days



# Function to predict closing price for a given date
def predict_closing_price(input_date):
    days = difference_in_days(input_date)
    lst_output=[]
    n_steps=100
    i=0
    while(i<100):
    
        if(len(temp_input)>100):
            #print(temp_input)
            x_input=np.array(temp_input[1:])
            print("{} day input {}".format(i,x_input))
            x_input=x_input.reshape(1,-1)
            x_input = x_input.reshape((1, n_steps, 1))
            #print(x_input)
            yhat = model.predict(x_input, verbose=0)
            print("{} day output {}".format(i,yhat))
            temp_input.extend(yhat[0].tolist())
            temp_input=temp_input[1:]
            #print(temp_input)
            lst_output.extend(yhat.tolist())
            i=i+1
        else:
            x_input = x_input.reshape((1, n_steps,1))
            yhat = model.predict(x_input, verbose=0)
            print(yhat[0])
            temp_input.extend(yhat[0].tolist())
            print(len(temp_input))
            lst_output.extend(yhat.tolist())
            i=i+1
    lst_output=scaler.inverse_transform(lst_output)
    return lst_output[0][99]

# Streamlit app
st.title("Stock Closing Price Predictor")

# Date input from user
input_date = input("Enter a date : ")

# Predict closing price when user submits the date
# if st.button("Predict Closing Price"):
predicted_price = predict_closing_price(str(input_date))
st.write(f"Predicted Closing Price for {input_date}: {predicted_price}")


Enter a date : 2023-01-02


UnboundLocalError: cannot access local variable 'temp_input' where it is not associated with a value

In [2]:
predicted_price

array([[2348.26654277],
       [2357.63330483],
       [2363.37493635]])

In [9]:
predicted_price[2]

array([2363.37493635])

In [13]:
import streamlit as st
from datetime import datetime
import numpy as np
import pandas as pd
from tensorflow.keras.models import load_model
from sklearn.preprocessing import MinMaxScaler
from numpy import array



# Load the saved model
model = load_model("stock_prediction_model.h5")

# Function to scale the input date
def difference_in_days(input_date):
    reference_date = datetime.strptime("2022-12-30", "%Y-%m-%d")
    input_date = datetime.strptime(input_date, "%Y-%m-%d")
    difference_in_days = (input_date - reference_date).days
    # scaled_input = (difference_in_days - scaler_min) / scaler_scale
    return difference_in_days


# Function to predict closing price for a given date
def predict_closing_price(input_date):
    days = difference_in_days(input_date)
    df=pd.read_csv('output.csv')
    df=df.tail(100)
    df1=df.reset_index()['high']

    scaler=MinMaxScaler(feature_range=(0,1))
    df1=scaler.fit_transform(np.array(df1).reshape(-1,1))

    x_input = df1[:,:1]
    x_input=x_input.reshape(1,-1)
    temp_input=list(x_input)
    temp_input=temp_input[0].tolist()
    lst_output=[]
    n_steps=100
    i=0
    while(i<100):
    
        if(len(temp_input)>100):
            #print(temp_input)
            x_input=np.array(temp_input[1:])
#             print("{} day input {}".format(i,x_input))
            x_input=x_input.reshape(1,-1)
            x_input = x_input.reshape((1, n_steps, 1))
            #print(x_input)
            yhat = model.predict(x_input, verbose=0)
#             print("{} day output {}".format(i,yhat))
            temp_input.extend(yhat[0].tolist())
            temp_input=temp_input[1:]
            #print(temp_input)
            lst_output.extend(yhat.tolist())
            i=i+1
        else:
            x_input = x_input.reshape((1, n_steps,1))
            yhat = model.predict(x_input, verbose=0)
#             print(yhat[0])
            temp_input.extend(yhat[0].tolist())
#             print(len(temp_input))
            lst_output.extend(yhat.tolist())
            i=i+1
    lst_output=scaler.inverse_transform(lst_output)
    return lst_output[90]

# Streamlit app
# st.title("Stock Closing Price Predictor")

# Date input from user
input_date = input("Enter a date : ")

# Predict closing price when user submits the date
# if st.button("Predict Closing Price"):
predicted_price = predict_closing_price(str(input_date))
st.write(f"Predicted Closing Price for {input_date}: {predicted_price}")


Enter a date : 2023-01-02


In [14]:
predicted_price

array([2467.30652386])

In [17]:
from datetime import datetime, timedelta


In [23]:
def difference_in_days(input_date):
    reference_date = datetime.strptime("2022-12-30", "%Y-%m-%d")
    input_date = datetime.strptime(input_date, "%Y-%m-%d")
    delta = timedelta(days=1)
    if input_date >= reference_date:
        difference_in_days = 0
        while input_date > reference_date:
            if input_date.weekday() < 5:  # Monday to Friday
                difference_in_days += 1
            input_date -= delta
        return difference_in_days
    else:
        return -(reference_date - input_date).days

In [24]:
difference_in_days("2020-12-30")

-730